include $(CLEAR_VARS)
LOCAL_MODULE := com.unisoc.sdk.common
LOCAL_SRC_FILES := framework/com.unisoc.sdk.common.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT_SYSTEM_EXT)/framework
LOCAL_UNINSTALLABLE_MODULE := true
include $(BUILD_PREBUILT)